export const AUTH_ENDPOINT = 'login'
export const FORGOT_PASSWORD_ENDPOINT = 'forgetPassword'
export const RESET_PASSWORD_ENDPOINT = 'resetPassword'
export const USERS_ENDPOINT = 'users'
export const USERS_CREATE_ENDPOINT = 'users/create'
export const USERS_STATUS_ENDPOINT = 'users/statusUpdate'
